movies/film/film/urls.py
from django.contrib import admin
from django.urls import path,include
from movie import views
from django.conf.urls.static import static
from django.conf import settings
app_name='movie'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie.urls')),
]


if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/film/movie/urls.py
from django.contrib import admin
from django.urls import path
from movie import views
from django.conf.urls.static import static
from django.conf import settings
app_name='movie'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('add/',views.add,name="add"),
    path('add1/',views.add1,name="add1"),
    path('view1/<int:p>',views.viewbyid,name="viewbyid"),
    path('deletebyid/<int:p>',views.delete,name="deletebyid"),
    path('editbyid/<int:p>',views.update,name="editbyid"),
]


if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movies/film/movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    image=models.ImageField(upload_to="books/cover",null=True,blank=True)
    name=models.CharField(max_length=20)
    description=models.CharField(max_length=20)
    year=models.IntegerField()

movies/film/movie/forms.py
from django import forms
from movie.models import Movie

class movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields='__all__'

movies/film/movie/views.py
from django.shortcuts import render
from movie.models import Movie
from movie.forms import movieform
# Create your views here.
def home(request):
    b=Movie.objects.all()
    return render(request,'home.html',{'movie':b})
def add(request):
    if(request.method=="POST"):
        img=request.FILES['im']
        name=request.POST['n']
        des=request.POST['d']
        year=request.POST['ye']
        b=Movie.objects.create(image=img,name=name,description=des,year=year)
        b.save()
        return home(request)
    return render(request,'add.html')
def add1(request):
    form=movieform()
    if(request.method=="POST"):
        form=movieform(request.POST,request.FILES)
        if(form.is_valid()):
            form.save()
            return home(request)
    return render(request,'add1.html',{'form':form})
def viewbyid(request,p):
    b=Movie.objects.get(id=p)
    return render(request,'view.html',{'m':b})
def delete(request,p):
    b=Movie.objects.get(id=p)
    b.delete()
    return home(request)
def update(request,p):
    b=Movie.objects.get(id=p)
    form=movieform(instance=b)
    if(request.method=="POST"):
        form=movieform(request.POST,request.FILES,instance=b)
        if(form.is_valid()):
            form.save()
            return home(request)
    return render(request,'add1.html',{'form':form})

movies/film/templates/add.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label>image</label>
    <input type="file" name="im"><br>
    <label>name</label>
    <input type="text" name="n"><br>
    <label>description</label>
    <input type="text" name="d"><br>
    <label>year</label>
    <input type="number" name="ye"><br>
    <input type="submit">
</form>

{% endblock %}

movies/film/templates/add1.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>add book-built in</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form.as_p }}
        </table>
    <input type="submit">
    </form>
{% endblock %}

movies/film/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/a.css' %}">
    <script src="{% static 'js/a.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container-fluid">

    <a class="navbar-brand" href="#"><b>movie</b></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'movie:home' %}">HOME</a>
        </li>



      </ul>
      <form class="d-flex">

        <a class="btn btn-success" href="{% url 'movie:add' %}">ADD</a>

      </form>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

movies/film/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>movies</h1>


<div class="container">

  <div class="row">
    {% for i in movie %}
    <div class="col-lg-4 p-3">
      <div class="card" style="width: 18rem;">

        <img src="{{i.image.url}}" class="card-img-top" height="200px" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">{{i.description}}</p>
          <a href="{% url 'movie:viewbyid' i.id %}" class="btn btn-primary">click</a>
        </div>
      </div>
    </div>

    {% endfor %}

  </div>


</div>


{% endblock %}

movies/film/templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>movie list</h1>
<table class="table table-hover">
    <tr class="table-secondary">
        <th>COVER</th>
        <td><img src="{{m.image.url}}" style="height:200px"></td>
    </tr>
    <tr>
        <th>name</th>
        <td>{{m.name}}</td>
    </tr>
    <tr>
        <th>description</th>
        <td>{{m.description}}</td>
    </tr>
    <tr>
        <th>year</th>
        <td>{{m.year}}</td>

    </tr>

</table>
<a class="btn btn-danger" href="{% url 'movie:editbyid' m.id %}">update</a>
<a class="btn btn-danger" href="{% url 'movie:deletebyid' m.id %}">delete</a>
{% endblock %}